name: Welcome to the party (El Cuarto)
on:
  workflow_dispatch:
jobs:
  say_hello:
    name: "Let's greet the user!"
    runs-on: ubuntu-latest
    steps:
      - id: get-time
        name: Grab the current time
        run: |
          cuTime=$(date)
          echo "current_time=$cuTime" >> $GITHUB_OUTPUT
      - run: echo "Welcome to Miami Beach, Pipooo poooo pipipopipopopipopo!! The current time is ${{ steps.get-time.outputs.current_time }}"  